services:
  - type: web
    name: secretys-backend
    env: node
    plan: starter
    buildCommand: "npm install && npx prisma generate"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: secretys-postgres
      - key: STRIPE_SECRET_KEY
        value: ""
      - key: STRIPE_WEBHOOK_SECRET
        value: ""
databases:
  - name: secretys-postgres
    plan: starter
